### ISSUE TITLE
Test Case

### ISSUE THREAD

**Issue by MariaC232** [SistemasTecTlaxiaco/practica-de-test-case-entrevista-equipo-cb-24h#2]
[Practica Test Case.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-test-case-entrevista-equipo-cb-24h/files/7347951/Practica.Test.Case.pdf)

**Comment by EDITH-R** [comment]
Calificación:20

**Comment by josealfredo79** [comment]
Bien hecho y revisada
